version: "3.3"
services:
      phpmyadmin: 
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: always
        ports:
          - 8899:80  
      backend-container:
       image: atallahdoc/tpachat
       container_name: tpachatback
       restart: on-failure
       ports:
         - 9090:9090
       environment:
          spring.datasource.url=jdbc:mysql://192.168.100.84:3306/TpAchat?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
       depends_on:
          - mysqldb
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       ports:
        - 3307:3306
       environment: 
        MYSQL_DATABASE: TpAchat
      
      
              