version: "3.3"
services:
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       ports:
        - "3306:3306"
      
      backend-container:
       image: atallahdoc/tpachat
       container_name: tpachatback
       restart: on-failure
       environment:
        spring.datasource.url: jdbc:mysql://192.168.100.84:33060/TpAchat?useSSl=false
        spring.datasource.username: root
        spring.datasource.password: root
       ports:
         - "9090:8080"
       depends_on:
         - mysqldb
              