version: 1.23
services:
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       ports:
        - "3307:3306"
      
      backend-container:
       image: atallahdoc/TpAchat
       container_name: TpAchat
       restart: on-failure
       environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
       ports:
          - 8090:8090
       depends_on:
          - mysqldb
              