version: "3.3"
services:
      backend-container:
       image: atallahdoc/tpachat
       container_name: tpachatback
       restart: on-failure
       ports:
         - "9090:9090"
       depends_on:
          - mysqldb
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       MYSQL_DATABASE: TpAchat
       ports:
        - "3307:3306"
      
      
              