version: "3.3"
services:
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       ports:
        - "3307:3306"
      
      backend-container:
       image: atallahdoc/tpachat
       container_name: tpachatback
       restart: on-failure
       ports:
         - "9090:8080"
       depends_on:
          - mysqldb
              