version: "3.3"
services:
      mysqldb:
       container_name: mysqldb
       image: mysql/mysql-server:8.0
       restart: unless-stopped
       ports:
        - "3307:3306"
      
      backend-container:
       image: atallahdoc/tpachat
       container_name: tpachatback
       restart: on-failure
       environment:
        - spring.datasource.url=jdbc:mysql://mysqldb:3306/achatdb?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
       ports:
          - 8090:8090
       depends_on:
          - mysqldb
              